# Generated by Django 5.2.3 on 2025-06-20 21:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('alunos', models.ManyToManyField(blank=True, limit_choices_to={'type': 'ALUNO'}, related_name='turmasAlunos', to=settings.AUTH_USER_MODEL)),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turmasDisciplina', to='ensino.disciplina')),
                ('monitores', models.ManyToManyField(blank=True, limit_choices_to={'type': 'MONITOR'}, related_name='turmasMonitores', to=settings.AUTH_USER_MODEL)),
                ('professor', models.ForeignKey(limit_choices_to={'type': 'PROFESSOR'}, on_delete=django.db.models.deletion.CASCADE, related_name='turmasProfessor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Turma',
                'verbose_name_plural': 'Turmas',
                'ordering': ['nome'],
            },
        ),
    ]
