# Generated by Django 5.2.3 on 2025-06-22 23:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('ensino', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacao',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publicacoes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='publicacao',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='comentario',
            name='autor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comentarios', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='autor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='forum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='ensino.forum'),
        ),
        migrations.AddField(
            model_name='comentario',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='ensino.post'),
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='posts', to='ensino.tag'),
        ),
        migrations.AddField(
            model_name='turma',
            name='alunos',
            field=models.ManyToManyField(blank=True, limit_choices_to={'type': 'ALUNO'}, related_name='turmasAlunos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='turma',
            name='disciplina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turmasDisciplina', to='ensino.disciplina'),
        ),
        migrations.AddField(
            model_name='turma',
            name='monitores',
            field=models.ManyToManyField(blank=True, limit_choices_to={'type': 'ALUNO'}, related_name='turmasMonitores', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='turma',
            name='periodo_letivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turmasPeriodoLetivo', to='ensino.periodoletivo'),
        ),
        migrations.AddField(
            model_name='turma',
            name='professor',
            field=models.ForeignKey(limit_choices_to={'type': 'PROFESSOR'}, on_delete=django.db.models.deletion.CASCADE, related_name='turmasProfessor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='publicacao',
            name='turma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publicacoes', to='ensino.turma'),
        ),
        migrations.AddField(
            model_name='forum',
            name='turma',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='forum', to='ensino.turma'),
        ),
    ]
