# Generated by Django 5.2.3 on 2025-06-21 20:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ensino', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='turma',
            name='alunos',
            field=models.ManyToManyField(blank=True, limit_choices_to={'type': 'ALUNO'}, related_name='turmasAlunos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='turma',
            name='disciplina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turmasDisciplina', to='ensino.disciplina'),
        ),
        migrations.AddField(
            model_name='turma',
            name='monitores',
            field=models.ManyToManyField(blank=True, limit_choices_to={'type': 'MONITOR'}, related_name='turmasMonitores', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='turma',
            name='professor',
            field=models.ForeignKey(limit_choices_to={'type': 'PROFESSOR'}, on_delete=django.db.models.deletion.CASCADE, related_name='turmasProfessor', to=settings.AUTH_USER_MODEL),
        ),
    ]
