# Generated by Django 5.2.3 on 2025-06-21 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ensino', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='disciplina',
            name='codigo',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='disciplina',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
    ]
