# Generated by Django 5.2.3 on 2025-06-22 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ensino', '0003_tag_forum_post_comentario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='resolvido',
        ),
    ]
